### ISSUE TITLE
Live Demo / Documentation Down

### ISSUE THREAD

**Issue by KarmicJohn** [MileanCo/angular-material-meteor-dashboard#2]
Is this still active? Any chance you could restart the demo server?

**Comment by MileanCo** [comment]
@KarmicJohn Yes it is still active! However, the newer version of this starter template is located here - https://github.com/MileanCo/angular-meteor-es6-dashboard-seed/  It uses the latest ES6 and Meteor version. 

The code is this repository uses Meteor <1.4 and ES5. As such, some of Meteor code is deprecated. Better to use the newer version above.

**Comment by MileanCo** [comment]
Either way, I've fixed the live demo! It's back online. 
Thanks for the heads up.
